"""ML scoring consumer worker for the SentryStream pipeline.

Consumes synthetic transactions from Kafka, persists them to PostgreSQL,
creates a placeholder fraud decision, and only then advances the Kafka offset.
"""

from __future__ import annotations

import json
import logging
import os
import signal
import sys
import hashlib
from pathlib import Path
from datetime import datetime
from decimal import Decimal
from typing import Any, Dict

import numpy as np
from xgboost import XGBClassifier
#import shap
import psycopg2
import redis
from kafka import KafkaConsumer
from kafka.consumer.fetcher import ConsumerRecord
from kafka.structs import OffsetAndMetadata, TopicPartition
from psycopg2.extras import Json


KAFKA_BOOTSTRAP_SERVERS = [os.getenv("SENTRYSTREAM_KAFKA_BROKER", "localhost:9094")]
KAFKA_TOPIC = "raw-transactions"
KAFKA_GROUP_ID = "sentrystream-ml-group"
MODEL_PATH = Path(__file__).with_name("fraud_model.json")
FEATURE_NAMES = ["Time"] + [f"V{index}" for index in range(1, 29)] + ["Amount"]

POSTGRES_CONFIG = {
    "host": os.getenv("SENTRYSTREAM_PGHOST", "127.0.0.1"), # Default to explicit IPv4 loopback
    "port": int(os.getenv("SENTRYSTREAM_PGPORT", "5433")),
    "dbname": os.getenv("SENTRYSTREAM_PGDATABASE", "sentrystream_db"),
    "user": os.getenv("SENTRYSTREAM_PGUSER", "sentrystream"),
    "password": os.getenv("SENTRYSTREAM_PGPASSWORD", "SentryStreamPass123"),
}

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
)
logger = logging.getLogger("sentrystream.ml_worker")


def build_consumer() -> KafkaConsumer:
    """Create a Kafka consumer with manual commit control."""

    return KafkaConsumer(
        KAFKA_TOPIC,
        bootstrap_servers=KAFKA_BOOTSTRAP_SERVERS,
        group_id=KAFKA_GROUP_ID,
        enable_auto_commit=False,
        auto_offset_reset="earliest",
        value_deserializer=lambda value: json.loads(value.decode("utf-8")),
        key_deserializer=lambda value: value.decode("utf-8") if value else None,
        consumer_timeout_ms=1000,
        max_poll_records=1,
    )


def build_database_connection():
    """Open a PostgreSQL connection for explicit transaction control."""

    connection = psycopg2.connect(**POSTGRES_CONFIG)
    connection.autocommit = False
    return connection


def load_model():
    """Load the saved mock XGBoost model from disk."""
    print("Step 1: Creating model")
    model = XGBClassifier()
    print("Step 2: About to load")
    model.load_model(MODEL_PATH)
    print("Step 3: Loaded!")
    return model


def build_explainer(model):
    """Create a TreeSHAP explainer for the loaded model."""
    import shap
    return shap.TreeExplainer(model)


def parse_timestamp(value: str) -> datetime:
    """Parse the ISO timestamp generated by the producer."""

    parsed = datetime.fromisoformat(value)
    if parsed.tzinfo is None:
        return parsed
    return parsed


def derive_model_features(transaction: Dict[str, Any]) -> np.ndarray:
    """Map a Kafka transaction into the exact 30-feature model input order."""

    feature_values = [float(transaction.get("Time", 0.0))]
    for index in range(1, 29):
        feature_values.append(float(transaction.get(f"V{index}", 0.0)))
    feature_values.append(float(transaction.get("Amount", transaction.get("amount", 0.0))))

    return np.array([feature_values], dtype=np.float32)


def explain_transaction(explainer, feature_vector: np.ndarray) -> Dict[str, Any]:
    """Compute a compact SHAP explanation for a single transaction."""

    shap_values = explainer.shap_values(feature_vector)
    if isinstance(shap_values, list):
        shap_array = np.asarray(shap_values[-1])[0]
    else:
        shap_array = np.asarray(shap_values)[0]

    ranked_features = sorted(
        zip(FEATURE_NAMES, shap_array.tolist()),
        key=lambda item: abs(item[1]),
        reverse=True,
    )

    return {
        name: round(float(value), 6)
        for name, value in ranked_features[:3]
    }


def persist_transaction(
    cursor,
    transaction: Dict[str, Any],
    is_fraud: bool,
    prediction_confidence: float,
    shap_explanation: Dict[str, Any],
) -> None:
    """Insert transaction and fraud decision rows idempotently."""

    transaction_timestamp = parse_timestamp(transaction["timestamp"])
    shap_explanation_json = json.dumps(shap_explanation)

    cursor.execute(
        """
        INSERT INTO transactions (
            transaction_id,
            card_id,
            amount,
            merchant,
            timestamp,
            location
        ) VALUES (%s, %s, %s, %s, %s, %s)
        ON CONFLICT (transaction_id) DO NOTHING
        """,
        (
            transaction["transaction_id"],
            transaction["card_id"],
            Decimal(str(transaction.get("Amount", transaction.get("amount", 0.0)))),
            transaction["merchant"],
            transaction_timestamp,
            transaction["location"],
        ),
    )

    cursor.execute(
        """
        INSERT INTO fraud_decisions (
            transaction_id,
            is_fraud,
            prediction_confidence,
            shap_explanation,
            processed_at
        ) VALUES (%s, %s, %s, %s, NOW())
        ON CONFLICT (transaction_id) DO NOTHING
        """,
        (
            transaction["transaction_id"],
            is_fraud,
            prediction_confidence,
            Json(json.loads(shap_explanation_json)),
        ),
    )


def process_message(
    consumer: KafkaConsumer,
    connection,
    model,
    explainer,
    message: ConsumerRecord,
) -> None:
    """Persist one Kafka message and commit its offset only after DB success."""

    transaction = message.value
    if not isinstance(transaction, dict):
        raise ValueError(f"Expected JSON object payload, received {type(transaction)!r}")

    feature_vector = derive_model_features(transaction)
    prediction_probability = float(model.predict_proba(feature_vector)[0][1])
    is_fraud = prediction_probability >= 0.5
    shap_summary = explain_transaction(explainer, feature_vector)

    cursor = connection.cursor()
    try:
        persist_transaction(
            cursor,
            transaction,
            is_fraud,
            prediction_probability,
            shap_summary,
        )
        connection.commit()

        alert_payload = {
            "transaction_id": transaction.get("transaction_id"),
            "card_id": transaction.get("card_id"),
            "amount": transaction.get("Amount", transaction.get("amount")),
            "merchant": transaction.get("merchant"),
            "location": transaction.get("location"),
            "timestamp": transaction.get("timestamp"),
            "is_fraud": is_fraud,
            "prediction_confidence": prediction_probability,
            "shap_explanation": shap_summary,
        }
        redis_client = redis.Redis(host=os.getenv("SENTRYSTREAM_REDIS_HOST", "127.0.0.1"),port=int(os.getenv("SENTRYSTREAM_REDIS_PORT", "6379")),decode_responses=True,)
        redis_client.publish("transaction-alerts", json.dumps(alert_payload))

        consumer.commit(
            offsets={
                TopicPartition(message.topic, message.partition): OffsetAndMetadata(
                    message.offset + 1,
                    None,      # matadata
                    -1     # leader_epoch
                )
            }
        )   ##Commit Kafka Offset
        logger.info(
            "Processed transaction_id=%s fraud_probability=%.4f partition=%s offset=%s",
            transaction.get("transaction_id"),
            prediction_probability,
            message.partition,
            message.offset,
        )
    except Exception:
        connection.rollback()
        raise
    finally:
        cursor.close()


def main() -> None:
    """Run the consumer worker until interrupted."""

    consumer = build_consumer()
    connection = build_database_connection()
    model = load_model()
    explainer = build_explainer(model)
    running = True

    def shutdown_handler(signum, frame):
        nonlocal running
        running = False
        logger.info("Received signal %s, shutting down...", signum)

    signal.signal(signal.SIGINT, shutdown_handler)
    signal.signal(signal.SIGTERM, shutdown_handler)

    try:
        while running:
            message_batch = consumer.poll(timeout_ms=1000, max_records=1)
            if not message_batch:
                continue

            for _partition, records in message_batch.items():
                for message in records:
                    if message is None or message.value is None:
                        continue

                    try:
                        process_message(consumer, connection, model, explainer, message)
                    except Exception:
                        logger.exception(
                            "Failed processing transaction at partition=%s offset=%s",
                            message.partition,
                            message.offset,
                        )
    finally:
        try:
            connection.close()
        finally:
            consumer.close()


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        logger.exception("Fatal worker error: %s", exc)
        sys.exit(1)